# configs/ablation_tmm.yaml
# Only keys you want to override from baseline.yaml

dataset_info:
  dataset_root: /raid/xvoice/nirmal/dataset/phoenix-2014-multisigner/

model_args:
  # TMM toggles
  c2d_type: resnet18
  enable_tmm: true
  tmm_location: "pre_bilstm"   # or "pre_bilstm"
  tmm_alpha: 0
  enable_motion: true

loss_weights:
  SeqCTC: 1.0
  ConvCTC: 1.0
  Dist: 25.0        # KD conv->seq stays as in baseline

# Optional: try greedy if you expose decode_mode in code
# decode_mode: "beam"  # or "max"

# Typical ablation grid you can try:
# - enable_tmm: [false, true]
# - tmm_location: ["pre_bilstm", "post_bilstm"]
# - enable_motion: [false, true]
# - Dist: [0.0, 25.0]


# To checkpoint models based on this metric score. 
# Original code selected the best WER among the 
# current epoch's Conv or LSTM WER. "best" is original/default
select_metric: "lstm" # "conv", "lstm", "best" 
