# dataset_root: /raid/xvoice/data/phoenix2014/phoenix-2014-multisigner
# dataset_root: /shared/home/xvoice/nirmal/SlowFastSign/dataset/phoenix2014/phoenix-2014-multisigner_original
# deblur_root: /shared/home/xvoice/nirmal/SlowFastSign/dataset/phoenix2014/phoenix-2014-multisigner
# dataset_root: /raid/xvoice/nirmal/phoenix-2014-multisigner_original
dataset_root: /nas/Dataset/Phoenix/phoenix2014-release/phoenix-2014-multisigner
# dataset_root: /shared/home/xvoice/nirmal/SlowFastSign/dataset/phoenix2014/phoenix-2014-multisigner # RVRT delburred dataset
# dataset_root: /raid/xvoice/nirmal/dataset/phoenix-2014-multisigner
# dataset_root: /raid/xvoice/data/phoenix2014/phoenix-2014-multisigner 
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-groundtruth
