batch_size: 4
config: ./configs/baseline.yaml
dataset: phoenix2014
dataset_info:
  dataset_root: /raid/xvoice/nirmal/phoenix-2014-multisigner
  dict_path: ./preprocess/phoenix2014/gloss_dict.npy
  evaluation_dir: ./evaluation/slr_eval
  evaluation_prefix: phoenix2014-groundtruth
decode_mode: beam
device: 0
dist_url: env://
eval_interval: 1
evaluate_tool: python
feeder: dataset.dataloader_video.BaseFeeder
feeder_args:
  datatype: video
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0
  input_size: 224
  mode: train
  num_gloss: -1
ignore_weights: []
load_checkpoints: false
load_weights: false
local_rank: 0
log_interval: 10000
loss_weights:
  ConvCTC: 1.0
  Dist: 25.0
  SeqCTC: 1.0
model: slr_network.SLRModel
model_args:
  c2d_type: resnet34
  conv_type: 2
  num_classes: 1296
  share_classifier: true
  use_bn: 1
  use_graph: false
  weight_norm: true
num_epoch: 80
num_worker: 4
optimizer_args:
  learning_rate:
    base_lr: 0.0001
  learning_ratio: 1
  nesterov: false
  num_epoch: 80
  optimizer: Adam
  scheduler: ScheaL
  start_epoch: 0
  step:
  - 20
  - 30
  - 35
  weight_decay: 0.0001
phase: train
print_log: true
random_fix: true
random_seed: 0
save_interval: 10
test_batch_size: 4
work_dir: ./deblurred_baseline/
world_size: 1
