_wandb:
    value:
        cli_version: 0.21.1
        e:
            09qhqmml80pd2bly6ibdp8orrc6256mu:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 36
                cpu_count_logical: 72
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "3672068382720"
                        used: "938065920000"
                email: adhikareen@inha.edu
                executable: /home/nirmal/miniconda3/envs/slr_bf16/bin/python
                git:
                    commit: 84ee64653d97567904e8a402bddfb24322efcaec
                    remote: git@github.com:Nirmal-Adhikari-hub/tmmNet.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-9153f649-3067-2e87-349e-4131227d74a1
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-9fe6b695-007a-4315-a8ff-855c16dca19e
                host: xvoice
                memory:
                    total: "269722030080"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/nirmal/SlowFast/ZtmmNet/main.py
                python: CPython 3.10.18
                root: ./deblurred_baseline
                startedAt: "2025-10-17T10:55:41.651256Z"
                writerId: 09qhqmml80pd2bly6ibdp8orrc6256mu
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "2": train_epoch/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": dev/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": test/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 6
              "6":
                - 1
              "7": []
            - "1": step
              "6": []
              "7": []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
                - 49
                - 63
                - 77
            "3":
                - 7
                - 13
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
